/* DO NOT EDIT THIS FILE
 * It is auto-generated by codeGen.py
 * from the Elderberry framework.
 */


#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <ev.h>
//headers

static void modules_initialize(int argc, char *argv[], struct ev_loop * loop){
//initfinal
}

//wiring

static void stop_cb(struct ev_loop *loop, ev_signal *w, int revents){
	ev_break(loop, EVBREAK_ALL);
}

int main(int argc, char *argv[]){

	int major = ev_version_major();
	int minor = ev_version_minor();
	if(!(major == EV_VERSION_MAJOR && minor >= EV_VERSION_MINOR)){
		errx(EXIT_FAILURE,
		     "Fatal: libev version mismatch. Expected %d.%d but got %d.%d",
		     EV_VERSION_MAJOR, EV_VERSION_MINOR, major, minor);
	}
	if(!ev_recommended_backends()){
		errx(EXIT_FAILURE, "Fatal: libev recommended backend not available");
	}

	struct ev_loop * loop;
	loop = ev_default_loop(0);
	if(!loop){
		errx(EXIT_FAILURE, "Fatal: could not initialize libev loop");
	}

	ev_signal stop;
	ev_signal_init(&stop, stop_cb, SIGINT);
	ev_signal_start(loop, &stop);
	modules_initialize(argc, argv, loop)
	ev_run(loop, 0);

	return EXIT_SUCCESS;
}
